config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :words
  get 'game/main_page'
  root to: 'game#main_page'
  get 'main', to: 'game#main_page'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,:rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
    # Kaminari
    paginates_per 20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :validate_word

  def main_page
    @words = Word.find(@randId)
  end

  private
  def validate_word
    @randId = randomId
    ids = Word.all.ids
    inside = ids.include?(@randId)
    msg = "#{ids} -> #{@randId} = #{inside}"
    if (!inside)
      showRandomWord(msg, 31)
      loop do
        @randId = randomId
        inside = ids.include?(@randId)
        msg = "[-] #{ids} -> #{@randId} = #{inside} "
        if (inside)
          msg += "=> #{Word.find(@randId).word}"
          showRandomWord(msg, 32)
          return @randId
        else
          showRandomWord(msg, 31)
        end
      end
    else
      msg += " => #{Word.find(@randId).word}"
      showRandomWord(msg, 32)
      return @randId
    end
  end

  def randomId
    r = Random.new
    r.rand(1...Word.all.size + 1)
  end

  def showRandomWord word, color
    puts "\033[1;#{color}m\n\n\n\n\t################# #{word} #################\n\n\n\n\033[m"
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all.page(params[:page])
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)
    @word.word = @word.word.split(" ")[0].upcase
    included = validate_new_word
    if !included
      respond_to do |format|
        if @word.save
          format.html { redirect_to new_word_path, notice: 'Word was successfully created.' }
          format.json { render :show, status: :created, location: @word }
        else
          format.html { render :new }
          format.json { render json: @word.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_word_path, notice: 'This word already exists.'
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word)
    end
    
    def validate_new_word
      included = Word.where(word: @word.word).exists?
      puts "\n\n\n+++++ #{@word.word} = #{included} ++++\n\n"
      included
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def toArray(word)
        word_array = word.upcase
        rand_letters = randLetter(word)
        word_array = rand_letters
        word_string = word.upcase
        return [word_array.shuffle!, word_string]
    end
    
    def randLetter(word_array)
        letters = []
        (0...5).each do |e|
            gene = (0...8).map { (65 + rand(26)).chr }.join
            gene = gene.split('')
            gene.each do |l|
                if (letters.include?(l))
                    next
                end
                letters << l
            end
        end
        word_array = word_array.split('')
        word_array.each do |l|
            if (!letters.include?(l))
                letters << l
            end
        end
        letters.shuffle!
    end

    def colorBody
        if params[:controller] == "words"
            "white"
        else
            "orange"
        end
    end
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/game/main_page.html.erb
<div class="container-main">
    <div class="box">
        <nav class="navbar navbar-light bg-danger">
        <%= link_to root_path, class:"text-white navbar-brand", onclick:"{location.reload()}" do %>
            <%= image_tag ('https://bit.ly/2Dx67Wk'), size: '30x30', class:"d-inline-block align-top", title:"Hangman Game" %>
            The Game!
        <% end %>
        </nav>
        <!--<h1>Hangman Game - Rails! </h1>-->
        <br>
        <h3 style="visibility:none">Health: <span id="health">4</span></h3>

        <div id="hearts" style="text-align: center; margin-right: 10px;display: inline-block;float: right;">
            <% 4.times do |i| %>
                <%= image_tag 'https://bit.ly/2BCFoHP', size:"40x40", id:"heart_#{i}" %>
            <% end %>
        </div>

        <% secret_word = @words.word  %>
        <% word = toArray(secret_word)[0] %>
        <!--<p>Secret word: <%= toArray(secret_word)[1] %></p>-->
        <br><br>
        <canvas style="border: 1px solid black;float:left;" onmousemove="showCoords(event)"></canvas>
        <br><br><br>

        <div id="showSecretWord" style="text-align: center;border: 0px solid black;margin-left: 350px;padding: 10px;color: red;visibility:hidden">
            <h2 style="font-size: 260%"><%= secret_word %></h2>
        </div>
        <br><br>

        <div style="text-align: center;" id="whiteEspaces">
            <% secret_word.size.times do |i| %>
                <h3 id="wE_<%= i %>">_</h3>
            <% end %>
        </div>
        <br>
        <div id='letters' class="letters">
            <% c = 0%>
            <% word.each do |e| %>

                <%= button_tag(type: 'button', id:c, class:"btn btn-primary shadow", value:e) do %>
                    <%= e %>
                <% end %>
                <% c+=1 %>
                
            <% end %>
        </div>
    </div>
</div>

<script>
    let canvas = document.querySelector('canvas')

    canvas.width = 350
    canvas.height = 430 // 450

    let c = canvas.getContext('2d')

    drawnStructure(10)

    function legs(height) {
        // left
        c.beginPath()
        c.moveTo(180, 300)
        c.lineTo(235, height + 155)

        // right
        c.moveTo(150 * 2, 300)
        c.lineTo(235, height + 155)

        c.lineWidth = 10;
        c.strokeStyle = 'blue'
        c.stroke()
    }

    function arms(height) {
        // left
        c.beginPath()
        c.moveTo(180, 170)
        c.lineTo(235, height + 20)

        // right
        c.moveTo(150 * 2, 170)
        c.lineTo(235, height + 18)

        c.lineWidth = 10;
        c.strokeStyle = 'blue'
        c.stroke()
    }

    function body() {
        c.fillStyle = 'blue'
        c.fillRect(231, 109, 10, 150)
    }

    function head() {
        c.lineWidth = 10;
        c.beginPath()
        c.arc(235, 75, 30, Math.PI * 2, false)
        c.strokeStyle = 'blue'
        c.stroke()
    }

    function drawnStructure(def = 0) {
        c.fillStyle = 'brown'
        c.fillRect(def, def, 10, 350)
        c.fillRect(def, def, 230, 10)
        c.fillRect(def, 350 + def, 130, 10)

        // corda
        c.fillStyle = 'black'
        c.fillRect(220+def, 10+def, 10, 20)

        // diagonal;
        c.beginPath()
        c.moveTo(def + 5, 100 + def)
        c.lineTo(100 + def, def + 5)
        c.lineWidth = 10;
        c.strokeStyle = 'brown'
        c.stroke()
    }

    function showCoords(event) {
        var x = event.clientX;
        var y = event.clientY;
        var coords = "X coords: " + x + ", Y coords: " + y;
        c.stroke()
        //document.getElementById("demo").innerHTML = coords;
    }





//////////////////////////////
    var el = document.getElementById('letters');
    el.addEventListener('click', function(e) {
        const id = e.target.id.toString()
        if (id === 'letters') { return }
        let  word= '<%= word.join('') %>'
        word = word.split("")
        var secret_word = ('<%= secret_word %>')
        var remaining = 4
        function logArrayElements(element, index, array) {
            var getValue = document.getElementById(id).value
            var value = getValue
            var inside = secret_word.includes(value)
            let keyPressed = getValue
            //console.log(inside)
            if (!inside) {
                var element = document.getElementById(id).className = "btn btn-danger";
                var health = document.getElementsByClassName("btn btn-danger").length * (-1) + remaining
                console.log(health)
                if (health === 3) {
                    head()
                } else if (health === 2) {
                    body()
                } else if (health === 1) {
                    arms(100)
                } else if (health === 0) {
                    legs(100)
                }
                heart = document.getElementById("heart_"+health)
                if (health === 0) {
                    $("#heart_"+health).addClass("disabledbutton")
                } else {
                    $("#heart_"+health).hide()
                }
                document.getElementById('health').innerHTML = health
                if (health == 0) {
                    document.getElementById("showSecretWord").style.visibility = "visible"
                    document.getElementById("health").className = "text-danger"
                    document.getElementById("health").innerHTML = "GAME OVER!"
                    disableDiv()
                    sleep(3000).then(() => {
                        location.reload()
                    })
                }
                return null
            } else {
                document.getElementById(id).className = "btn btn-success";
                pushLetters(secret_word, keyPressed)
                let corrects = document.getElementsByClassName("btn btn-success").length
                let notWhiteEspaces = document.getElementsByName("not_wE").length
                let allCorrects = corrects === secret_word.length || secret_word.length === notWhiteEspaces
                if (allCorrects ) {
                    document.getElementById("health").className = "text-success"
                    document.getElementById("health").innerHTML = "CONGRATULATIONS!"
                    disableDiv()
                    sleep(3000).then(() => {
                        location.reload()
                    })
                }
            }
        }
        word.forEach(logArrayElements);
    })

    const pushLetters = (secret_word, keyPressed) => {
        for (let pos in secret_word) {
            if (secret_word[pos] === keyPressed) {
                document.getElementById(`wE_${pos}`).innerHTML = keyPressed;
                $('#wE_' + pos).attr('name', 'not_wE');
            }
        }
    }

    const disableDiv = _ => {
        $("#letters").addClass("disabledbutton")
    }
    
    const sleep = (milliseconds) => {
        return new Promise(resolve => setTimeout(resolve, milliseconds))
    }
</script>

app/views/layouts/_footer.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<br>
<footer id="myFooter">
    <div class="social-networks">
        <%= link_to url_for("https://github.com/devlucasrocha/Hangman_Game"), class:"github", target:"blank" do %>
        <i class="fa fa-github" style="font-size: 190%;"></i>
        <% end %>
    </div>
    <div class="footer-copyright">
        <%= link_to url_for("https://github.com/devlucasrocha"), target:"blank" do %>
            <p style="padding: 5px">© 2019 github.com/devlucasrocha</p>
        <% end %>
    </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangman Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body style="background-image: url('https://chupacdn.s3.amazonaws.com/catalog/product/cache/5/thumbnail/1280x/17f82f742ffe127f42dca9de82fb58b1/3/-/3-set-nature-and-desert-game-background-14764_imgs_14764_3.png');">
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :word %>
    <%= form.text_field :word, class:"form-control", placeholder:"Enter some word", required:true %>
  </div>

  <div class="actions">
    <%= form.submit nil, class:"btn btn-primary" %>
  </div>
<% end %>

<script>
  $(function() {
      $('#word_word').on('keypress', function(e) {
          if (e.which == 32)
              return false;
      })
  })
</script>

app/views/words/edit.html.erb
<br>
<div class="container-fluid container">
    <h1 class="display-4 bg-white p-2">Editing Word</h1>
    <div class="jumbotron">
        <%= render 'form', word: @word %>
        <br>
        <%= link_to 'Show', @word, class:"btn btn-primary" %> |
        <%= link_to 'Back', words_path, class:"btn btn-primary" %>
    </div>
</div>

<% 10.times do |a| %>
    <br>
<% end %>

app/views/words/index.html.erb
<div class="text-right mr-3 mt-3 mb-3">
  <%= link_to('Logout', destroy_admin_session_path, method: :delete, class:"btn btn-danger", style:"border: 3px solid white;")%>
</div>
<div class="container-fluid">
  <div class="container">
  <h1 class="display-4 bg-white p-2">RANDOM WORDS DATABASE</h1>
    <table class="table bg-white table-hover text-center">
      <thead class="thead-dark">
        <tr>
          <th>ID</th>
          <th>Word</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @words.each do |word| %>
          <tr>
            <td><strong><%= word.id %></strong></td>
            <td><%= word.word %></td>
            <td><%= link_to 'Show', word %></td>
            <td><%= link_to 'Edit', edit_word_path(word) %></td>
            <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <div class="container pagination justify-content-center" >
      <%= paginate @words, pagination_class: "pagination-sm" %>
    </div>
  </div>
</div>
<br>

<div class="text-center">
  <%= link_to 'New Word', new_word_path, class:"btn btn-primary" %>
</div>
<% if !notice.nil? %>
    <script>
        new Noty({
          theme: 'nest',
          type: 'success',
          layout: 'topRight',
          text: '<%= notice %>'
        }).show();
    </script>
<% end %>

app/views/words/new.html.erb
<br>
<div class="container-fluid container">
    <h1 class="display-4 bg-white p-2">New Word</h1>
    <div class="jumbotron">
        <%= render 'form', word: @word %>
        <br>
        <%= link_to 'Back', words_path, class:"btn btn-primary" %>
    </div>
</div>
<% 10.times do |e| %>
    <br>
<% end %>

<% if !notice.nil? %>
    <% alreadyExist = notice.include?("already") %>
    <% colorMsg = "" %>
    <% if alreadyExist %>
        <% colorMsg = 'error' %>
    <% else %>
        <% colorMsg = 'success' %>
    <% end %>
        <script>
            new Noty({
                    theme: 'nest',
                    type: '<%= colorMsg %>',
                    layout: 'topRight',
                    text: '<%= notice %>'
            }).show();
        </script>
<% end %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid container">
  <h1 class="display-4 bg-white p-2">Showing Word</h1>
    <div class="jumbotron">
      <div class="form-group">
        <strong>Word:</strong>
        <%= text_field_tag nil, @word.word, class:"form-control", placeholder:"Enter some word", disabled:true %>
      </div>

      <%= link_to 'Edit', edit_word_path(@word), class:"btn btn-primary" %> |
      <%= link_to 'Back', words_path, class:"btn btn-primary" %>
  </div>
</div>

<% 10.times do |a| %>
  <br>
<% end %>